spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: bounce
  config:
    import: security-variable.yml
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bounce?serverTimezone=Asia/Seoul
    username: root
    password: ${mysql.password}

mybatis:
  classpath:
  mapper-locations: mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

    spring:
      jpa:
        hibernate:
          ddl-auto: none
        show-sql: false